ir_site_project_list:
    path:     /
    defaults: { _controller: IRSiteBundle:Project:index }
    methods:  [GET]

ir_site_projects_issue_list:
    path:     /projects/{projectId}/issues
    defaults: { _controller: IRSiteBundle:Issue:index }
    methods:  [GET]

ir_site_projects_comment_list:
    path:     /projects/{projectId}/comments
    defaults: { _controller: IRSiteBundle:Comment:index }
    methods:  [GET]
    requirements:
        id:  \d+
ir_site_projects_comment_add:
    path:     /projects/{projectId}/comments/add
    defaults: { _controller: IRSiteBundle:Comment:add }
    methods:  [PUT]
    requirements:
        id:  \d+