ir_site_auth_login:
    path:     /login
    defaults: { _controller: IRSiteBundle:Auth:login }
    methods:  [GET]
ir_site_auth_loginCheck:
    path:     /login_check
    defaults: { _controller: IRSiteBundle:Auth:securityCheck }
    methods:  [POST]
ir_site_auth_logout:
    path:     /logout
    defaults: { _controller: IRSiteBundle:Auth:logout }

ir_site_project_list:
    path:     /
    defaults: { _controller: IRSiteBundle:Project:index }
    methods:  [GET]

ir_site_projects_issue:
    path:     /projects/{projectId}
    defaults: { _controller: IRSiteBundle:Issue:index }
    methods:  [GET]
ir_site_projects_issue_list:
    path:     /projects/{projectId}/issues
    defaults: { _controller: IRSiteBundle:Issue:getIssuesByTracker }
    methods:  [GET]
ir_site_projects_issue_trackTime:
    path:     /projects/{projectId}/issues/{issueId}
    defaults: { _controller: IRSiteBundle:Issue:trackTime }
    methods:  [GET|PUT]

ir_site_projects_comment_list:
    path:     /projects/{projectId}/comments
    defaults: { _controller: IRSiteBundle:Comment:index }
    methods:  [GET]
    requirements:
        id:  \d+
ir_site_projects_comment_add:
    path:     /projects/{projectId}/comments/add
    defaults: { _controller: IRSiteBundle:Comment:add }
    methods:  [PUT]
    requirements:
        id:  \d+