ir_redmine_api:
    resource: "@IRRedmineAPIBundle/Resources/config/routing.yml"
    prefix:   /

ir_site:
    resource: "@IRSiteBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
